language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - 1.1
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; pkg"build QSWalk";'
  - julia --code-coverage test/runtests.jl 
after_success:
- julia --depwarn=no -e 'using Pkg; cd(Pkg.dir("QSWalk")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
- julia -e 'using Pkg; ps=Pkg.PackageSpec(name="Documenter", version="0.19"); Pkg.add(ps); Pkg.pin(ps)'
- julia -e 'using Pkg; cd(Pkg.dir("QSWalk")); include(joinpath("docs", "make.jl"))'

