name = "QSWalk"
uuid = "2ef04bfc-99ca-5394-8b07-22b12ff94927"
keywords = ["quantum walk", "quantum computing", "GKSL"]
desc = "Simulator for stochastic quantum walk"
authors = ["Adam Glos <aglos@iitis.pl>", "Jarosław Adam Miszczak <jmiszczak@iitis.pl>", "Mateusz Ostaszewski <mostaszewski@iitis.pl>"]
licence = "MIT"
version = "1.0.2"

[compat]
julia = "1"

[deps]
Expokit = "a1e7a1ef-7a5d-5822-a38c-be74e1bb89f4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"


[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targest]
test = ["SparseArrays", "LinearAlgebra", "Test"]
